file = open("read.txt")
# lines =file.readlines()
# print(lines, type(lines))

# line1 = file.readline()
# print(line1)
# line2 = file.readline()
# print(line2)
# line3 = file.readline()
# print(line3)
# line4 = file.readline()
# print(line4)
# line5 = file.readline()
# print(line5)
lines =file.readline()

while(lines!= ""):
    print(lines)
    lines = file.readline()
file.close()