s = set()

n = int(input("enter your no.1 : "))
s.add(n)
n2 = int(input("enter your no.2 : "))
s.add(n2)
n3 = int(input("enter your no.3 : "))
s.add(n3)
n4 = int(input("enter your no.4 : "))
s.add(n4)
n5 = int(input("enter your no.5 : "))
s.add(n5)
n6 = int(input("enter your no.6 : "))
s.add(n6)
n7 = int(input("enter your no.7 : "))
s.add(n7)
n8 = int(input("enter your no.8 : "))
s.add(n8)

print(s)